# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: simple-kafka-cluster
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: loadbalancer
      tls: false
      configuration:
        bootstrap:
          annotations:
            networking.gke.io/load-balancer-type: "Internal"
        brokers:
        - broker: 0
          advertisedHost: kafka-brok-0.kafka.demo.io
          annotations:
            networking.gke.io/load-balancer-type: "Internal"
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
