apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: simple-kafka-cluster
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: loadbalancer
      tls: false
      configuration:
        bootstrap:
          annotations:
            networking.gke.io/load-balancer-type: "Internal"
        brokers:
        - broker: 0
          advertisedHost: kafka-brok-0.kafka.demo.io
          annotations:
            networking.gke.io/load-balancer-type: "Internal"
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
